version: '3.8'
services:
  api:
    image: hangout-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000